package rs.ac.uns.ftn.informatika.osa.pr04;

/**
* rs/ac/uns/ftn/informatika/osa/pr04/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rs/ac/uns/ftn/informatika/osa/pr04/Hello.idl
* Wednesday, June 26, 2013 11:02:27 AM CEST
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public rs.ac.uns.ftn.informatika.osa.pr04.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (rs.ac.uns.ftn.informatika.osa.pr04.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = rs.ac.uns.ftn.informatika.osa.pr04.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    rs.ac.uns.ftn.informatika.osa.pr04.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return rs.ac.uns.ftn.informatika.osa.pr04.HelloHelper.type ();
  }

}
