package rs.ac.uns.ftn.informatika.osa.pr04;


/**
* rs/ac/uns/ftn/informatika/osa/pr04/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rs/ac/uns/ftn/informatika/osa/pr04/Hello.idl
* Wednesday, June 26, 2013 11:02:27 AM CEST
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
